<h2>Kmom10: Färdigställ och produktifiera MVC-ramverket</h2>
<p><strong>Krav k1: Installera från GitHub</strong><br/>
GitHub har varit lite mödosamt att lära sig. Att behöva använda sig av DOS-liknande kommandon är inte något jag är van vid eller hade förväntat mig använda. Men, med tid och med repetition så kan jag utföra de kommandon jag känner till snabbt, men bli i princip hopplöst förlorad i googling och för mig svårlästa manualer. Men till GitHubs försvar så är det väldigt bra för att dela med sig av kod, och att bara kunna clona något direkt i GitBash är smidigt och snabbt. Att behöva tänka på ramverket för nya användare har också tagit fram vissa problem, så som att förhindra fula kraschar när sidan inte blivit initierad än, eller att vissa filer kan bara ges rätt rättigheter om ramverket skapar dem åt användaren. En sådan sak var <code>style.css</code>, som inte kunde skrivas över när jag kopierade från kmom07 till kmom10, men när jag tog bort filen och lät ramverket skapa nytt så fungerade det utan problem.
  </p>
<p><strong>Krav k3: Ett anpassningsbart ramverk</strong><br/>
Jag hade så gärna velat skapa ett webbgränssnitt för det här, men bara administreringsfunktionerna, som jag tyckte kändes häftigare, tog i slutändan en enorm mängd tid. Så dessvärre sköts konfigureringen i <code>config.php</code> för tillfället, när jag hellre hade sett ett snyggt formulär som fixade det och att det lagrades i databasen. Men jag är imponerad av ramverkets (Lydia dvs) temahantering och även de CSS-ramverk som jag fått testa på under kursen. Grid, LESS och semantic.gs har gett mig mer verktyg än jag trott var möjligt för CSS, och hade jag inte varit så förlorade i PHP och SQL så kan jag se mycket nytta av temahantering med dessa gratis ramverk. Älskar det! Mina största problem har nog varit att få <code>less.php</code> att faktiskt skapa filerna korrekt, då i många fall så har cache-filen varit helt tom, style-filen har inte gått att skriva över eller så har jag helt enkelt glömt att ändra mapprättigheterna. 
  </p>
<p><strong>Krav k4: Ett administrativt gränssnitt (optionellt)</strong><br/>
Här fick jag riktigt gräva ner mig, och hade det väldigt kul... ett tag i alla fall. Att läsa och hantera databaser känns dynamiskt så det var svårt att stoppa, men när jag väl kom in på korsreferens av ungefär tre databaser i samma query så fick jag stopp. Det går inte enkelt att söka efter på google då det är så specifikt, och även när jag hittade något jag trodde skulle fungera så gjorde det inte. Det jag behövde nämligen var ett sätt lista upp vilka grupper en användare INTE tillhörde för att skapa en dropdown-lista (som jag lade till i CForm) där man enkelt kunde se vilka grupper som fanns och vilka man kunde lägga in användaren i. Det slutade i alla fall upp med att SQL var omöjligt att hantera för mig, och att det istället handlade om arrays. I min faktiskt fungerande lösning så hämtade jag då användarens 'memberships' och all data om alla grupper som finns i databasen och hämtade dess ID-värden. Sedan använde jag mig av <code>array_intersect()</code> med dessa IDn för att finna dem som användaren kunde gå med i. Därefter så fungerade det inte heller för en väldigt lång tid, men med <code>current()</code> så kunde jag gå ett steg ur arrayen som av någon anledning nästlat sig djupare än vad jag trott, och nu... efter FLERA timmar över kanske tre dagar så gick det. Tror jag aldrig varit så arg på min datorskärm i hela mitt liv som jag varit under kmom10.
  </p>
<p><strong>Beskriv din testinstallation, gick den smidigt att göra eller var det något som krånglade, borde ramverket varit annorlunda?</strong><br/>

  </p>
<p><strong>Vad tycker du om kursen?</strong><br/>
Det är helt enkelt för mycket att ta in. Jag vet att jag gick med på 100% studietakt, men jag har fått skippa påskfirandet och jobbat sent och alltid lite efter. Men det är såklart inte allt på er, utan jag har alla möjligheter att fråga efter hjälp, kursen har många vägar att be efter råd... jag är väl för svensk bara antar jag. En sak däremot som hjälpte mig vid ett annat migränanfall var att en viss shorthand som jag såg i Lydias kod med <code>->setTitle...</code>, var att jag frågade i chatten och fick reda på att funktioner som använder sig av detta måste använda sig av <code>return $this;</code>. Det stör mig ganska mycket att det kommer in i exempelkoden men inte förklaras, då det är VÄLDIGT svårt att förstå vad det är som faktiskt är fel.
Så för att summera så är jag imponerad över vad jag har framför mig och hur pass mycket jag förstått av det, men även hur pass mycket jag inte förstår heller. Allting med den här kursen har varit att stressa sig igenom åtskilliga sidor, ramverk, länkar, övningar, obeskrevliga problem och lösa trådar för att komma fram till en häftig sida. Frågorna man ska besvara i slutet av varje uppgift känns nästan lite hånande när man ska fråga om man hade läst igenom X ramverks dokumentation eller gjort övriga uppgifter, det är nästan orealistiskt för åtminstone mig som är helt ny till MVC/CMF. Så... tagga ner lite.
  </p>
  Projektet kan du hitta på <a href="https://github.com/andrige/neurosis">GitHub</a>